#!/bin/bash

export GUROBI_HOME="/opt/gurobi702/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"

if [ -z "${LD_LIBRARY_PATH}" ]
then
	export LD_LIBRARY_PATH="${GUROBI_HOME}/lib"
else
	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
fi
